stages:
- name: build docker image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: stunnel
- name: deploy to homelab
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: cicd
    notifier: local:n-2rfpx
  condition:
  - Success
  - Changed
  - Failed
