stages:
- name: build docker image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: stunnel
      pushRemote: true
      registry: registry.networkcover.com:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: deploy to homelab
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: cicd
    notifier: local:n-2rfpx
  condition:
  - Success
  - Changed
  - Failed
